services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3999  # Points to the backend service in Docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
