version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3001  # Updated to reflect the backend service URL
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend  # Assuming your Go backend Dockerfile is in the ./backend directory
      dockerfile: Dockerfile  # Update if your Dockerfile has a different name
    ports:
      - "3001:3001"  # Expose the port your Go application listens on
    volumes:
      - ./backend:/app  # Mount the backend code into the container for easy development
